### ISSUE TITLE
Processing not finding Phidgets C

### ISSUE THREAD

**Issue by ghost** [sgeigers/Phidgets-For-Processing#1]
as of sept 2016
osx 10.10.5

processing 3.2.1
latest drivers from Phidgets

it seems this is a common problem

I have added the libphidget21.jnilib to both the System / Library / java / extensions  
and the Library / java / extensions 

there is also a copy in usr/local/lib

where is your Jar file looking for the libs?

oH -> also I tried "Add File" in the PDE adding both the jnilib and the JAR files

thanks for any help

HI again!!!
so adding the libphidget21.jnilib file to the /Users/gato/Documents/Processing/libraries/PhidgetsForProcessing/library
made it work

(I'm getting errors still that the device in not attached - but thats different)

G

**Comment by sgeigers** [comment]
It's good to know it works. I couldn't make Phidgets work with Processing on Mac, so I wrote the library is for Windows platforms only at this time. I'll try to organize it to work on macs "straight from the box" using your tip.
Thanks.

**Comment by ghost** [comment]
yeah sigh
got the library to work (it runs)
but the encoder example - what I'm trying to use
now has a runtime error of " PhidgetException 5 (Phidget not physically attached.) "

the phidgets test app see it fine both in the general and the webserver tabs

any thoughts would be very appreciated

**Comment by sgeigers** [comment]
What board do you use?

**Comment by ghost** [comment]
Hi
I'm using the PhidgetEncoder HighSpeed 4-Input
http://www.phidgets.com/products.php?product_id=1047
connected to a very standard encoder

**Comment by sgeigers** [comment]
Can you check it on a windows platform - to see if the problem lies there?

**Comment by ghost** [comment]
Sadly I don't have a windows machine at the moment.
we are a Mac and Linux house

**Comment by sgeigers** [comment]
I didn't check it on linux, but if it's available to you - won't hurt to try.
Checked it again on PC and it works fine.
Another option is to check a different Phidget board on the Mac (if you have any), and see if that works.

**Comment by ghost** [comment]
hmmmmmm very strange stuff
I just tried changing the line...
  encoder = new Encoder(this);
to   encoder = new Encoder(SERIALNUMBER OF BOARD);

which of course errored
but then when I changed it back to the proper
  encoder = new Encoder(this);

the program them worked...

--for real --

so it smells like there is something not initializing correctly
but it does work!
(well now there's an error in the drawing code... but that's visual)

Hum   crazy   - but  BINGO

thanks

**Comment by sgeigers** [comment]
I'll try to solve the Mac problem the moment I can put my hands on one.
Thanks, and please keep updating if you find anything new.

**Comment by sgeigers** [comment]
OK.
Now it should also work for mac.

**Comment by ghost** [comment]
yay!
