### ISSUE TITLE
Phidgets 22

### ISSUE THREAD

**Issue by RafSilva** [sgeigers/Phidgets-For-Processing#3]
Hello I'm trying to use the first examples, but it's not detecting the phidgets boards. It works fine in the control panel but processing does not detect.
"Error: no phidget board attached"
"PhidgetException 5 (Phidget not physically attached.)"

I think this might be because of using Phidgets 22 instead of 21, I tried installing the legacy 21 version in:
https://www.phidgets.com/docs21/OS_-_Windows
But it won't detect in the control panel the phidgets neither on processing nor on the control panel.

I think maybe the code needs to be updated for Phidgets 22 or am I missing something ( I went through the troubleshooting steps)

Thanks.

**Comment by sgeigers** [comment]
Hello,
Yes - the library currently only supports Phidgets21, and thus supports
only the older modules.
What Phidget are you using?

**Comment by RafSilva** [comment]
Ok, thank you.
